name: terraform validate

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '.github/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: hashicorp/setup-terraform@v2
    - run: terraform init
    - id: validate
      run: terraform validate -no-color
